/**
 * ✨ TURBOMODULE IMPLEMENTATION (.mm file)
 * 
 * KEY DIFFERENCES FROM LEGACY:
 * 1. File extension: .mm (Objective-C++) - allows C++ code for JSI
 * 2. Has getTurboModule method - enables JSI direct calls
 * 3. Returns C++ shared_ptr with JSI bindings
 * 4. No need for RCT_EXPORT_METHOD macro (spec defines it)
 * 5. Type-safe method signatures from Codegen
 * 6. Lazy loaded on first use
 * 7. Direct JavaScript-to-Native calls (bypasses bridge)
 */

#import "DeviceInfoModule.h"
#import <UIKit/UIKit.h>

@implementation DeviceInfoModule

// Standard module export (same for both TurboModule and Legacy)
RCT_EXPORT_MODULE()

// 🔑 KEY DIFFERENCE #1: No RCT_EXPORT_METHOD macro needed
// Legacy: Requires RCT_EXPORT_METHOD(getDeviceInfo:reject:)
// TurboModule: Method signature already defined in Codegen spec
- (void)getDeviceInfo:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject {
  @try {
    UIDevice *device = [UIDevice currentDevice];
    
    NSDictionary *deviceInfo = @{
      @"model": device.model ?: @"Unknown",
      @"manufacturer": @"Apple",
      @"osVersion": device.systemVersion ?: @"Unknown",
      @"deviceId": [[[device identifierForVendor] UUIDString] ?: @"Unknown"],
      @"brand": @"Apple"
    };
    
    resolve(deviceInfo);
  } @catch (NSException *exception) {
    reject(@"ERROR", @"Failed to get device info", nil);
  }
}

// 🔑 KEY DIFFERENCE #2: THIS IS THE MAGIC METHOD! getTurboModule enables JSI
// Legacy: Doesn't have this method at all
// TurboModule: This method enables:
//   - Direct JSI (JavaScript Interface) calls
//   - Bypasses React Native Bridge
//   - No JSON serialization needed
//   - Synchronous calls possible
//   - Lazy loading (loads only when first used)
//   - Better performance (~60% faster)
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  // 🔑 Returns auto-generated JSI binding class
  // NativeDeviceInfoModuleSpecJSI is generated by React Native Codegen
  // from the TypeScript spec in src/specs/NativeDeviceInfoModule.ts
  return std::make_shared<facebook::react::NativeDeviceInfoModuleSpecJSI>(params);
}

@end
